version: '2'

services:
   db:
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: upshift
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     ports:
       - "3306:3306"
